#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#define CRYSTALLESS    1

#define VENDOR_NAME "NeKuNeKo Inc."
#define PRODUCT_NAME "Kitten Display (SAMD21)"
#define VOLUME_LABEL "DSPLAY-BOOT"
#define INDEX_URL "https://github.com/nekuneko/"
#define BOARD_ID "SAMD21E18A-Kitten-Display"

#define USB_VID 0x1993
#define USB_PID 0x0326

#define LED_PIN PIN_PA16

#define BOARD_NEOPIXEL_PIN PIN_PA18
#define BOARD_NEOPIXEL_COUNT 1

#define BOOT_USART_MODULE SERCOM2
#define BOOT_USART_MASK APBAMASK
#define BOOT_USART_BUS_CLOCK_INDEX MCLK_APBAMASK_SERCOM2
#define BOOT_USART_PAD_SETTINGS UART_RX_PAD1_TX_PAD0
#define BOOT_USART_PAD3 PINMUX_UNUSED
#define BOOT_USART_PAD2 PINMUX_UNUSED
#define BOOT_USART_PAD1 PINMUX_PA09D_SERCOM2_PAD1
#define BOOT_USART_PAD0 PINMUX_PA08D_SERCOM2_PAD0
#define BOOT_GCLK_ID_CORE SERCOM2_GCLK_ID_CORE
#define BOOT_GCLK_ID_SLOW SERCOM2_GCLK_ID_SLOW

#endif
